name: Deploy Go Server

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5.0.2

    - name: Build Go binary
      run: |
        cd backend
        go build -o server

    - name: Deploy to Alpine Linode
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        scp -i private_key server root@194.195.253.151:~/test StrictHostKeyChecking=no
        rm private_key
