name: Deploy Go Server

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5.0.2
      with:
        go-version: '1.23'  # Adjust the Go version as needed

    - name: Build Go binary
      run: |
        cd backend
        GOOS=linux GOARCH=amd64 go build -o server

    - name: Deploy to Alpine Linode
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no ./backend/server root@194.195.253.151:~/test
                ssh -i private_key -o StrictHostKeyChecking=no root@194.195.253.151 << 'EOF'
          chmod +x ~/test/server
          # Optionally, list files to verify
          ls -l ~/test/server
          # Attempt to run the server
          ~/test/server
        EOF
        rm private_key
